version = 1

test_patterns = ["**/__tests__/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "jest",
    "nodejs"
  ]
  plugins = ["react"]
  dialect = "typescript"

[[transformers]]
name = "prettier"
enabled = true
