name: Integration

on:
  pull_request:
    branches:
    - master
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Echo integration
      run: echo "integration"

    - name: Echo branch name
      run: echo $GITHUB_HEAD_REF

    - name: Echo hello branch
      run: echo "hello $GITHUB_HEAD_REF"

    - name: Echo PR number
      run: echo "PR number {{ github.event.number }}"
