name: Integration

on:
  pull_request:
    branches:
    - master
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Cache Node dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Install dependencies
      run: yarn install --no-progress --non-interactive

    - name: Build integration pipeline
      run: yarn --cwd integration-pipeline build

    - name: Deploy integration pipeline
      run: yarn --cwd integration-pipeline deploy --no-staging --require-approval never
      env:
        GITHUB_HEAD_REF=$GITHUB_HEAD_REF
        GITHUB_PR_NUMBER=${{ github.event.number }}
