name: Integration Teardown

on:
  pull_request:
    branches:
    - master
    types: [closed]

jobs:
  teardown-integration:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Cache Node dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Install dependencies
      run: yarn install --no-progress --non-interactive

    - name: Build infrastructure
      run: yarn --cwd cloud-infrastructure build

    - name: Teardown AWS S3 integration UI bucket
      run: aws s3 rb s3://static-app-${{ github.event.number }} --force

    - name: Teardown AWS S3 integration event log bucket
      run: aws s3 rb s3://eventlog-integration-${{ github.event.number }} --force

    - name: Teardown AWS S3 integration pipeline artifact bucket
      run: aws s3 rb s3://deploymentpipeline-integration-${{ github.event.number }} --force

    - name: Destroy integration infrastructure
      run: yarn --cwd cloud-infrastructure destroy --force
      env:
        GITHUB_PR_NUMBER: ${{ github.event.number }}

    - name: Build integration pipeline
      run: yarn --cwd integration-pipeline build

    - name: Destroy integration pipeline
      run: yarn --cwd integration-pipeline destroy --force
      env:
        GITHUB_PR_NUMBER: ${{ github.event.number }}
